[project]
name = "django-logs-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-mock>=3.14.0",
]
